### ISSUE TITLE
training issues

### ISSUE THREAD

**Issue by hanyaning** [BarCodeReader/SelfReformer#16]
Thank you very much for your code! When conducting phase environment configuration and starting training, the following problems occur. What might be the cause?
please!
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main()
  File "main.py", line 38, in main
    solver.fit()
  File "/data2/cnu_hyn/SelfReformer-main/solver.py", line 53, in fit
    for i, inputs in enumerate(tqdm(self.train_loader)):
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data2/cnu_hyn/SelfReformer-main/data/__init__.py", line 60, in __getitem__
    MASK = color.rgb2gray(MASK)  # shape of [h, w]
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/skimage/_shared/utils.py", line 326, in fixed_func
    return func(*args, **kwargs)
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/skimage/color/colorconv.py", line 875, in rgb2gray
    rgb = _prepare_colorarray(rgb)
  File "/data2/cnu_hyn/envs/selfReformer/lib/python3.8/site-packages/skimage/color/colorconv.py", line 140, in _prepare_colorarray
    raise ValueError(msg)
ValueError: the input array must have size 3 along `channel_axis`, got (267, 400)

**Comment by BarCodeReader** [comment]
ValueError: the input array must have size 3 along channel_axis, got (267, 400)

please check the data you used. the error says the data need to be an RGB image (3 in channel axis), but got a single-channel image. you can write a script to check the image shape and find out which image is giving this issue.

**Comment by hanyaning** [comment]
Thank you for your answer. I am using the DUTS-TR dataset, but this issue still arises

**Comment by BarCodeReader** [comment]
check your sk-image version, the error comes from
https://github.com/BarCodeReader/SelfReformer/blob/c95d07e7d97a045d82d5244fc1eb8aea5c0937e8/data/__init__.py#L54

for my environment, sk-image is **0.16.2**
or check [this solution](https://github.com/ocampor/image-quality/issues/41)

We need to change the GT into the same format. DUTS-TE or DUTS-TR have both single-channel and 3-channel GT images, so that is why we need this line of code.

if you really cannot solve it, change skimage to PIL. The code is replicable by others, so I suggest you check skimage version or modify the code to fit your environment. Since it is just a color transformation, it's fine if you change to other image process packages like PIL or cv2.

Cheers

**Comment by hanyaning** [comment]
This issue has been resolved, thank you for your help!Thank you again for providing the code！
