### ISSUE TITLE
Unpickling error when trying to load the pretrained model on DUTS

### ISSUE THREAD

**Issue by ck090** [BarCodeReader/SelfReformer#7]
I am currently getting the following error when trying to load the model.

Traceback (most recent call last):
  File "/projects/chna2810/SelfReformer/main.py", line 42, in <module>
    main()
  File "/projects/chna2810/SelfReformer/main.py", line 25, in main
    tester = Tester(module, opt)
  File "/projects/chna2810/SelfReformer/tester.py", line 19, in __init__
    self.net = module.Net(opt)
  File "/projects/chna2810/SelfReformer/model/network.py", line 14, in __init__
    self.encoder = Encoder()
  File "/projects/chna2810/SelfReformer/model/Encoder_pvt.py", line 13, in __init__
    self.encoder.load_state_dict(torch.load('./model/pretrain/pvt_v2_b2.pth', map_location='cpu'), strict=False)
  File "/projects/chna2810/software/anaconda/envs/new_a100/lib/python3.9/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/projects/chna2810/software/anaconda/envs/new_a100/lib/python3.9/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'._

Any help would be appreciated.

**Comment by allenyidan** [comment]
May be the problem of github cause this error for the large size cpt file. try to download  the pvt checkpoint from the original site https://github.com/whai362/PVT.

**Comment by ck090** [comment]
Cool. This works, thank you!
